### ISSUE TITLE
onCancle 传入没有执行

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-popover#10]
这个方法只定义了defaultProps 没有接收props.onCancle的方法

**Comment by eternalsky** [comment]
只有 onCancel ，没有 onCancle ，给个 Demo 来浮现一下吧，http://codepen.io/eternalsky/pen/qZwNVL

**Comment by peng2e** [comment]
拼写错误 。 就是onCancel  传入了不起作用。 @eternalsky   说白了，onCancel 这个api就没用。。。

**Comment by eternalsky** [comment]
实测是有效果的，可否用 codepen 来一个 复现 demo？

**Comment by peng2e** [comment]
貌似版本问题，刚才重新nowa lib了一下，可以了。  ^_^!
