### ISSUE TITLE
如何在InputFormField上加上popover?

### ISSUE THREAD

**Issue by WClouds** [uxcore/uxcore-popover#11]
在InputFormField上加上Popover不管用？请问是为什么啊

**Comment by eternalsky** [comment]
Popover 需要一层 dom 元素。请提供 demo，方便跟踪定位问题~

**Comment by WClouds** [comment]
`
  render() {
    let overlay = (
      <div>
        <div className="demoContent">
          <i className="kuma-icon kuma-icon-information"></i>
          <span>This is a demo</span>
        </div>
      </div>
    );
    return (
      <Form ref="form">
        <Popover overlay={overlay}>
          <InputFormField
            jsxrules={[
                { validator: Validators.isNotEmpty, errMsg: '请输入邮箱。' },
                { validator: Validators.isEmail, errMsg: '邮箱格式非法。' },
            ]}
            validateOnBlur
            jsxname="email"
            jsxplaceholder="邮箱"
            jsxshowLabel={false}
          />
        </Popover>
      </Form>
    );
  }
`

**Comment by eternalsky** [comment]
FormField 必须是 Form 的直接子元素才可以（考虑到 Form 的值管理及布局），其他的元素加进去也不会理会，如果你只是为了给 input 加上说明的话，建议使用 jsxtips，如果坚持要使用，Poppover 套 FormFIeld，请不要套用 Form，直接使用 FormField，但这样的情况下，校验取值等操作需要你自行完成。

**Comment by WClouds** [comment]
`

        <Tooltips placement="right" trigger={['focus']} overlay={tipOverlay}>
          <input
            className={classnames({
              'kuma-input': true,
              'kuma-uxform-input-has-right': !!count || !!rightAddon,
              'kuma-uxform-input-has-left': !!leftAddon,
            })}
            ref="root"
            key={me.props.inputType}
            type={me.props.inputType}
            placeholder={placeholder}
            disabled={(me.props.jsxdisabled === 'disabled' || me.props.jsxdisabled === true)
               ? 'disabled' : ''}
            name={me.props.key}
            value={me.state.formatValue}
            onFocus={me.handleFocus}
            onBlur={me.handleBlur}
            onChange={me.handleChange}
            onKeyDown={me.handleKeyDown}
            {...otherOptions}
          />
        </Tooltips>
`
我直接在InputFormField中在input 上面加了rc-tooltip，可以实现tooltip的效果了，准备再改一下FormField组件，把renderErrorMsg和renderTips调成可开关的，这样就可以选择用tooltip显示还是用原来的jsxtips显示了

**Comment by eternalsky** [comment]
目前只考虑 jsxtips 对应的显示方式，浮出 tip 不在 设计考虑范围。
